---
- name: Install mariaDB database- server
  hosts: databases
  gather_facts: true
  become: true
  vars:
    - mysql_root_password: "tutp610125"
  tasks:
    - name: install mariadb & python3-PyMySQL
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: set mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"
        host: localhost
    - name: configure firewall
      yum:
        name: firewalld
        state: present
    - name: start firewall service
      service:
        name: firewalld
        state: started
        enabled: true
    - name: configutr zones
      firewalld:
        zone: database
        state: present
        permanent: yes
    - name:
      firewalld:
        source: 192.168.3.9
        state: enabled
        permanent: yes
    - name: set the database source
      firewalld:
        port: 3306/tcp
        state: enabled
        permanent: yes
    # - name: configure django
    #   firealld:
    #     name: django
    #     host: "%password=12345"
    #     priv: "*.*:ALL"
    #     state: present
    - name: remove remote root
      mysql_user:
        check_implicit_admin: true
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        host: "{{ ansible_fqdn }}"
        state: absent
